"""Tests for exposing the externally-synced MuSCAT2 quicklook dashboard.

The dashboard (obslog, quicklook, airmass plot) is generated on the MuSCAT2
observing host and synced to MUSCAT2_HTML_DIR by a job outside muscat-db.
muscat-db exposes it read-only via two StaticFiles mounts (see
``_mount_muscat2_quicklook``) and a link on the muscat2 instrument page and
the obs page, mirroring the existing /tess-quicklook link-out pattern rather
than reimplementing the dashboard's own UI.
"""

from __future__ import annotations

from fastapi import FastAPI
from fastapi.testclient import TestClient

from muscat_db.web import _mount_muscat2_quicklook, app


def test_mount_serves_dashboard_and_the_airmass_absolute_path_alias(tmp_path):
    """airmass_plot/index.html (regenerated by the remote observing host)
    hardcodes an absolute image src of /airmass_plot/png/<date>/...png, so the
    compatibility mount at root must resolve it even though the dashboard
    itself is served under the /lc-monitor prefix."""
    html_dir = tmp_path / "html"
    png_dir = html_dir / "airmass_plot" / "png" / "260101"
    png_dir.mkdir(parents=True)
    (html_dir / "index.html").write_text("<h1>MuSCAT2 dashboard</h1>", encoding="utf-8")
    (png_dir / "plot.png").write_bytes(b"fake-png-bytes")

    test_app = FastAPI()
    assert _mount_muscat2_quicklook(test_app, html_dir) is True

    client = TestClient(test_app)
    assert "MuSCAT2 dashboard" in client.get("/lc-monitor/").text
    assert client.get("/airmass_plot/png/260101/plot.png").status_code == 200


def test_obslog_and_archive_directories_get_a_listing_instead_of_404(tmp_path):
    """obslog/ and quicklook/archive/ have no index.html in the real synced
    tree, so the dashboard mount must use the listing-capable StaticFiles
    subclass rather than plain StaticFiles (which 404s on a bare directory)."""
    html_dir = tmp_path / "html"
    (html_dir / "obslog" / "260101").mkdir(parents=True)
    (html_dir / "obslog" / "260101" / "obslog-muscat2-260101-ccd0.html").write_text("<p>log</p>")
    (html_dir / "index.html").write_text("<h1>MuSCAT2 dashboard</h1>")

    test_app = FastAPI()
    assert _mount_muscat2_quicklook(test_app, html_dir) is True

    resp = TestClient(test_app).get("/lc-monitor/obslog/")
    assert resp.status_code == 200
    assert '<a href="260101/">260101/</a>' in resp.text


def test_mount_is_skipped_when_the_synced_directory_is_absent(tmp_path):
    """Hosts without the /ut2 mount (e.g. a dev machine or CI) must still
    start cleanly, with no dead /lc-monitor route registered."""
    test_app = FastAPI()
    missing_dir = tmp_path / "does-not-exist"

    assert _mount_muscat2_quicklook(test_app, missing_dir) is False
    assert TestClient(test_app).get("/lc-monitor/").status_code == 404


def test_mount_is_skipped_when_index_html_lives_under_muscat2_subdir(tmp_path):
    """index.html lives under the muscat2/ subdirectory on the observing host
    (it moved there from the html root), so pointing MUSCAT2_HTML_DIR at the
    top-level synced tree must fall back to the muscat2/ subtree when present."""
    html_dir = tmp_path / "html"
    (html_dir / "muscat2" / "obslog" / "260101").mkdir(parents=True)
    (html_dir / "muscat2" / "index.html").write_text("<h1>MuSCAT2 dashboard</h1>")

    test_app = FastAPI()
    assert _mount_muscat2_quicklook(test_app, html_dir / "muscat2") is True

    resp = TestClient(test_app).get("/lc-monitor/")
    assert resp.status_code == 200
    assert "MuSCAT2 dashboard" in resp.text


def test_instrument_page_links_to_the_dashboard_only_for_muscat2_when_available(
    mock_db, monkeypatch,
):
    client = TestClient(app)

    monkeypatch.setattr("muscat_db.web.LC_MONITOR_AVAILABLE", True)
    assert 'href="/lc-monitor/"' in client.get("/muscat2").text
    assert "Live LC Monitor" not in client.get("/muscat3").text

    monkeypatch.setattr("muscat_db.web.LC_MONITOR_AVAILABLE", False)
    assert "Live LC Monitor" not in client.get("/muscat2").text


def test_obs_page_links_to_the_dashboard(mock_db, monkeypatch):
    client = TestClient(app)

    monkeypatch.setattr("muscat_db.web.LC_MONITOR_AVAILABLE", True)
    assert 'href="/lc-monitor"' in client.get("/obs").text

    monkeypatch.setattr("muscat_db.web.LC_MONITOR_AVAILABLE", False)
    assert 'href="/lc-monitor"' in client.get("/obs").text


def test_lc_monitor_dead_link_redirects_to_quicklook():
    """The synced index.html's "Quicklook" link points at lc_monitor, which
    has never existed in the synced tree (a pre-existing typo); the real
    content lives at quicklook/. This route is registered unconditionally, so
    it redirects the same way regardless of whether the dashboard itself is
    mounted on this host."""
    resp = TestClient(app).get("/lc-monitor/lc_monitor", follow_redirects=False)

    assert resp.status_code in (301, 302, 303, 307, 308)
    assert resp.headers["location"] == "/lc-monitor/quicklook/"
