#!/usr/bin/env bash
# Entry point of the muscatdb-worker@<host>-<pipeline> systemd user unit
# (generated by deploy/workers.py). Not meant to be run by hand.
#
# The password lives in the file named by MUSCAT_WORKER_PG_ENV (pg.env, mode
# 600) and is read here, at start, so it is never written to a unit, an
# environment file or this repo. Only the host and database are swapped.
set -euo pipefail

instance="${1:?usage: worker-run.sh <host>-<pipeline>}"
pipeline="${instance##*-}"
repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

env_file="${MUSCAT_WORKER_PG_ENV:?MUSCAT_WORKER_PG_ENV is not set}"
env_file="${env_file/#\~/$HOME}"
# shellcheck disable=SC1090
source "$env_file"

dsn="${MUSCAT_POSTGRES_DSN:?MUSCAT_POSTGRES_DSN missing from $env_file}"
dsn="${dsn%/*}/${MUSCAT_WORKER_PG_DATABASE:?MUSCAT_WORKER_PG_DATABASE is not set}"
export MUSCAT_POSTGRES_DSN="${dsn/@localhost:/@${MUSCAT_WORKER_PG_HOST:?MUSCAT_WORKER_PG_HOST is not set}:}"

cd "$repo"
exec "$repo/.venv/bin/muscat-db" worker --pipeline "$pipeline"
